### ISSUE TITLE
Use TypeInfo for reflection 

### ISSUE THREAD

**Issue by BeeWarloc** [Pomona/Pomona#107]
To make stuff PCL compatible, should be straightforward as we only support netfx 4.5 and higher.

**Comment by asbjornu** [comment]
@BeeWarloc: How does this relate to #129?

**Comment by BeeWarloc** [comment]
Not sure if this is needed for .NET Core 2.0 or not.

**Comment by BeeWarloc** [comment]
Guess we'll find out later, if it's required it won't compile anyway so safe to close this.
