### ISSUE TITLE
Query using != true on nullable bool property results in "Failed to execute query"

### ISSUE THREAD

**Issue by timorzadir** [Pomona/Pomona#62]
.Where(x => x.BoolProperty != true)

**Comment by BeeWarloc** [comment]
Seem to work just fine in Pomona right now, might have been fixed at some point..

**Comment by BeeWarloc** [comment]
@timorzadir: is this working for you now?

**Comment by BeeWarloc** [comment]
@timorzadir if I remember correctly we figured this one out. I think maybe it had something to do with NHibernate, but I'm not quite sure.

Closing this, reopen if you disagree :)
