### ISSUE TITLE
Use roslyn or maybe T4 templates for client generation

### ISSUE THREAD

**Issue by BeeWarloc** [Pomona/Pomona#64]
No need to struggle with complicated IL generation code when compiling from C# is easy and cheap.

This might take quite a bit of work to accomplish, but I think it would be worth the effort in the long run. Would be nice to remove the ugliest piece of code (`ClientLibGenerator.cs`)

**Comment by asbjornu** [comment]
I'd be the first one to cheer if we could delete `ClientLibGenerator.cs`! :clap: I do, however, have a strong preference on Roslyn over T4 if and when we implement `ClientLibGenerator.vnext`.

**Comment by BeeWarloc** [comment]
I will close this, as I can't see this getting priority in the near future.
