### ISSUE TITLE
Figure out type names for container types (arrays, query results, etc..)

### ISSUE THREAD

**Issue by BeeWarloc** [Pomona/Pomona#65]
The current serialization format uses type name "__results__" for all query results.
Should type of query results be serialized as "QueryResult<Resource>", or would introducing generics be  a unnecessary complication?

Pro generic support:
* Makes it easier to know what type to deserialize to, without having to think about expected return type.
Con:
* Too much noise?

**Comment by asbjornu** [comment]
Could you paste some serialization examples so uninitiated people like myself could better understand the involved implications? :)

**Comment by BeeWarloc** [comment]
```
```


```
{
  "$type": "QueryResult<Farm>",
  "items": [
    {
      "$ref": "http://test/farms/71"
    },
    {
      "$ref": "http://test/farms/72"
    },
    {
      "$ref": "http://test/farms/215"
    },
    {
      "$ref": "http://test/farms/216"
    }
  ],
  "next": null,
  "previous": null,
  "skip": 0,
  "totalCount": -1
}
```

**Comment by BeeWarloc** [comment]
Current serialization format:

```json
{
  "_type": "__result__",
  "totalCount": -1,
  "items": []
}
```

New serialization format?
```json
{
  "$type": "QueryResult<Farm>",
  "totalCount": -1,
  "items": []
}
```

**Comment by GeirGrusom** [comment]
What is the point of exposing the query type to the consumer? The deserialization collection I would think is unimportant to the consumer, and could even be a hindrance in certain deserialization scenarios.

**Comment by BeeWarloc** [comment]
@GeirGrusom yeah, you are right. I don't believe I really have a good reason for that.

It would probably be better to just leave out the "$type" entirely. The idea was to make it possible to deserialize the object without actually knowing its type, as that is slightly more practical to implement.

I will try to just leave leave it up to the consumer. Maybe use `$items` instead of `items` to use that as a general convention for a collection plus some additional information.
