### ISSUE TITLE
Implement Storyteller for examples in documentation

### ISSUE THREAD

**Issue by asbjornu** [Pomona/Pomona#84]
[Storyteller](https://storyteller.github.io/) makes it easier to keep examples used in documentation in sync with working code, since the examples themselves are pulled from compiled and tested code within the repository. We should investigate using Storyteller for all inline code examples used in the documentation.

**Comment by asbjornu** [comment]
Testing Slack integration

**Comment by BeeWarloc** [comment]
We can't use existing tests if I understand this correct, they have to be adopted for use with Storyteller?

**Comment by asbjornu** [comment]
Yes, I believe the code snippets have to be especially tailored for the examples, but at least the code will be "alive", compiled and executed along with the rest of the code base an tests.

**Comment by BeeWarloc** [comment]
There is now a branch with work-in-progress documentation on the https://github.com/Pomona/Pomona/tree/feature/storyteller-docs branch.

We have to wait until the Storyteller PR https://github.com/storyteller/Storyteller/pull/515 is merged before we can set up publication through CI.

For now I have a set up manually updated preview at http://pomona.io/preview/

**Comment by asbjornu** [comment]
@BeeWarloc Great work! :+1:
